### ISSUE TITLE
Support react hooks api: server bundle broken because of "Hooks can only be called inside the body of a function component"

### ISSUE THREAD

**Issue by TotooriaHyperion** [JounQin/react-server-renderer#18]
at /local/GitHub/react-server-renderer/src/bundle-renderer/create-bundle-renderer.ts:116:17 name: 'Invariant Violation', framesToPop: 1 }
Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

**Comment by TotooriaHyperion** [comment]
Looks like should be solved by react team several months later.

**Comment by TotooriaHyperion** [comment]
说中文会方便些，

https://github.com/JounQin/react-server-renderer/blob/f34189bd4c2b9b95571c11b6b05a9f152e26174a/src/create-renderer.ts#L53

在这里的react-dom/server是当前运行环境的。
而他所得到的component对象是在sandbox里evaluate得到的。

这里就导致了react和react-dom处于不同的环境。

而react hooks中的ReactCurrentDispatcher是要求两者处于同一环境的。

因此会触发这个错误。

综上所述，react官方的意思是，在使用ssr的时候，应该由开发者自行调用ReactDOMServer和React来返回一个string，而不是由外部的renderer进行render。

所以这个库目前的方案看来是无法兼容react-hooks的。

简单的解决办法是，entry-server中国由用户自行调用renderToString，然后返回string而不是vdom对象。

在

https://github.com/JounQin/react-server-renderer/blob/f34189bd4c2b9b95571c11b6b05a9f152e26174a/src/create-renderer.ts#L53

中
result = typeof component === "string" ? component : renderToString(component);

**Comment by JounQin** [comment]
不好意思，有段时间没有使用 React 服务端渲染了，这个礼拜才有空看了一下，实际上使用 `runInNewContext: false` 选项是不会创建新的 sandbox 而是在 `runInThisContext` 里执行脚本，导致 react hooks 报错是 `react-async-bootstraper/react-async-component` 不兼容导致的，我切换到 `react-loadable` 使用没有问题。


https://github.com/JounQin/react-hackernews/blob/master/src/components/Comment/index.js#L13

https://react-hackernews-zopiqyqufy.now.sh/top
